sudo: false
language: php

cache:
  apt: true
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

matrix:
  include:
    - php: 7.1
      env: WP_TRAVISCI=grunt

before_script:
  - nvm install stable
  - npm install -g grunt-cli
  - npm install
  - npm --version
  - node --version

script:
  - grunt --version
  - grunt default
