sudo: false
language: php

env:
  global:
    - HP_KEY_FILE="deploy_rsa"
    - HP_BUILD_DIR="happyprime"

addons:
  ssh_known_hosts: 23.239.25.212

cache:
  apt: true
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change

matrix:
  include:
    - php: 7.1
      env: WP_TRAVISCI=grunt

before_script:
  - nvm install stable
  - npm install -g grunt-cli
  - npm install
  - npm --version
  - node --version

script:
  - grunt --version
  - grunt default
  - make build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_d52879560fb1_key -iv $encrypted_d52879560fb1_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/$HP_KEY_FILE
  - ssh-add /tmp/$HP_KEY_FILE

deploy:
  provider: script
  skip_cleanup: true
  script:
    - rsync -r --delete-after --quiet --rsync-path="mkdir -p /home/deploy/$TRAVIS_REPO_SLUG-$TRAVIS_BRANCH && rsync" $TRAVIS_BUILD_DIR/$HP_BUILD_DIR deploy@23.239.25.212:/home/deploy/$TRAVIS_REPO_SLUG-$TRAVIS_BRANCH
  on:
    all_branches: true
